# name: Testing
# on: push

# jobs:
#   test_project:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Run Django unit tests
#       run:
#         pip3 install --user django
#         python3 manage.py test
name: Testing

on:
  push:
    branches:
      - main  # Change this to your default branch name if it's different

jobs:
  test_project:
    runs_on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Replace 'x' with the desired Python version

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install django

    - name: Run Django unit tests
      run: |
        python3 manage.py test